name: Linter
'on':
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:
jobs:
  sonarcloud:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3