name: Linter
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 16 * * *
jobs:
  sonarcloud:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3